name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Application
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Staging
        run: |
          sshpass -p "${{ secrets.CPanel_PASSWORD }}" rsync -avz --delete ./.next/ ${CPanel_USER}@$103.213.38.117:public_html/staging

      - name: Staging Deployment Completed
        run: echo "Staging deployment complete visit https://stage.portfolio.himelrana.com"