name: Deploy to Production

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Production Dependencies
        run: npm install --production

      - name: Build Next.js Application
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Production
        run: |
          sshpass -p "${{ secrets.CPanel_PASSWORD }}" rsync -avz --delete ./.next/ ${CPanel_USER}@${CPanel_HOST}:public_html/portfolio
          
      - name: Completed Production Deployment
        run: echo "Production deployment visit https://himelrana.com"